### PR TITLE
Update

### PR DESCRIPTION
**Pull request by FayasNoushad**
- Added pyrogram link
- Updated runtime
- Changed session name to repository name
- Updated callback data
- Removed unused return
- Added authorised user filter for broadcast
- Fixed commas

### CODE REVIEW

**Comment by MrBotDeveloper** [comment]
But filters.user() Method doesn't works for multiple users it's only limited upto one user as far as I know

So, [this](https://github.com/nacbots/BroadcastBot/pull/2/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L83) is more better way I think 🥲

**Comment by FayasNoushad** [comment]
> But filters.user() Method doesn't works for multiple users it's only limited upto one user as far as I know
> 
> So, [this](https://github.com/nacbots/BroadcastBot/pull/2/files#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L83) is more better way I think

Ohh! Sorry I don't know about that. Fixed, check now.

**Comment by MrBotDeveloper** [comment]
Thanks bro 🥲

**Comment by FayasNoushad** [comment]
Always welcome 😁

**Comment by MrBotDeveloper** [comment]
🤘

**Pull request merged**
